name: Python 3.8 compatibility

on:
  push:
    branches: [ dev ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Gpytranslate
        run: python setup.py install

      - name: Run tests
        run: |
          cd tests
          python -m unittest
